global:
  name: appdir-b0e0efb5-app-insights-ui-deployment-dev
  namespace: app-insights-dev
  host: randoli.ca


volumes:
  - name: app-insights-ui-keycloak-config-cm-volume
    configMap:
      name: app-insights-ui-keycloak-config
      defaultMode: 420

serviceAccountName: app-insights-ui-sa-dev
serviceAccount: app-insights-ui-sa-dev


# File: values.yaml

labels:
  app: my-app
  environment: production
  tier: backend

