global:
  name: my-deployment
  namespace: default

containers:
  name: my-container

configmapReload:
  prometheus:
    resources:
      image: "my-prometheus-image:latest"

env:
  secrets:
    - refName: my-secret-ref
      fileName: my-secret-file

language: go

spec:
  containers:
    volumeMounts:
      - name: my-volume
        mountPath: /path/to/mount
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080

serviceAccountName: my-service-account
serviceAccount: my-service-account
imagePullSecrets: my-image-pull-secret
