{{- if ( .Values.configMap.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
    labels: { { - tpl ("metadata.labels" | toYaml) . | nindent 4 } }
    name: { { .Values.global.name } }
    namespace: { { .Values.global.namespace } }
data:
    {{ .Values.config.data }}
{{- end }}
