apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "metadata.labels" | nindent 4 }}
  annotations:
    {{- include "metadata.annotations" | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spec.matchLabels" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metadata.labels" | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.containers.name }}
      {{- with .Values.configmapReload.prometheus.resources }}
        image: >-
        {{- toYaml . | nindent 12 }}  
      {{- end }}
        ports:
          {{- include "container.ports" | nindent 8 }}
        envFrom:
        {{- if .Values.env.secrets }}
            {{- range .Values.env.secrets }}
            - {{ .refName }}
              name: {{ .fileName }}
            {{- end }}
        {{- end }}
          resources:
            {{- if eq .Values.language "go" }}
            limits:
              cpu: 50m
              memory: 60Mi
            requests:
              cpu: 50m
              memory: 60Mi
            {{- end }}
            {{- if eq .Values.language "java-spring-boot" }}
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
            {{- end }}
            {{- if eq .Values.language "java-quarkus" }}
            limits:
              cpu: 50m
              memory: 120Mi
            requests:
              cpu: 25m
              memory: 100Mi
            {{- end }}
          imagePullPolicy: Always
        {{- if .Values.spec.containers.volumeMounts }}
          volumeMounts:
            {{- include "spec.containers.volumeMounts" | nindent 8 }}
        {{- end}}
        {{- if .Values.spec.containers.volumeMounts }}
          livenessProbe:
            {{- include "spec.containers.livenessProbe" | nindent 8 }}
        {{- end}}
      serviceAccountName: {{ .Values.serviceAccountName }}
      serviceAccount: {{ .Values.serviceAccount }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}