apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- tpl ("metadata.labels" | toYaml) . | nindent 4 }}
  annotations:
    {{- tpl ("metadata.annotations" | toYaml) . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- tpl ("spec.matchLabels" | toYaml) . | nindent 3 }}
  template:
    metadata:
      labels:
        {{- tpl ("metadata.labels.test" | toYaml) . | nindent 4 }}
    spec:
      containers:
      - name: {{ .Values.containers.name }}
      {{- with .Values.configmapReload.prometheus.resources }}
        image: >-
        {{- toYaml . | nindent 12 }}  
      {{- end }}
        ports:
          {{- tpl ("container.ports" | toYaml) . | nindent 5 }}
        envFrom:
        {{- if .Values.env.secrets }}
            {{- range .Values.env.secrets }}
            - {{ .refName }}
              name: {{ .fileName }}
            {{- end }}
        {{- end }}
          resources:
          {{- if eq .Values.language "go" }}
            limits:
              cpu: 50m
              memory: 60Mi
            requests:
              cpu: 50m
              memory: 60Mi
          {{- end }}
          {{- if eq .Values.language "javaSpringBoot" }}
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
          {{- end }}
          {{- if eq .Values.language "java-quarkus" }}
            limits:
              cpu: 50m
              memory: 120Mi
            requests:
              cpu: 25m
              memory: 100Mi
          {{- end }}
          imagePullPolicy: Always
        {{- if .Values.spec.containers.volumeMounts }}
          volumeMounts:
            {{- tpl ("spec.containers.volumeMounts" | toYaml) . | nindent 6 }}
        {{- end}}
        {{- if .Values.spec.containers.volumeMounts }}
          livenessProbe:
            {{- tpl ("spec.containers.livenessProbe" | toYaml) . | nindent 6 }}
        {{- end}}
      serviceAccountName: {{ .Values.serviceAccountName }}
      serviceAccount: {{ .Values.serviceAccount }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}