{{- if ( .Values.externalSecret.enabled) -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  labels:
    {{- tpl ("metadata.labels" | toYaml) . | nindent 4 }}
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  backendType: {{ .Values.externalSecret.backendType }}
  data:
    {{- tpl ("externalSecret.spec.data" | toYaml) . | nindent 4 }}
  kvVersion: {{ .Values.externalSecret.kvVersion }}
  vaultRole: {{ .Values.externalSecret.vaultRole }}
{{- end }}

