{{- if ( .Values.ingress.enabled) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: { { - tpl ("metadata.annotations" | toYaml) . | nindent 4 } }
  labels: { { - tpl ("metadata.labels" | toYaml) . | nindent 4 } }
  name: { { .Values.global.name } }
  namespace: { { .Values.global.namespace } }
spec:
  rules:
    - host: { { .Values.global.host } }
      http:
        paths:
          - backend:
              service:
                name: { { .Values.global.name } }
                port:
                  number: { { .Values.ingress.port } }
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - { { .Values.global.host } }
      secretName: { { .Values.secret.name } }
{{- end }}
