{{- if ( .Values.service.enabled) -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- tpl ("metadata.labels" | toYaml) . | nindent 4 }}
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      targetPort: {{ .Values.serviceMonitor.targetPort }}
      path: {{ .Values.serviceMonitor.path }}
  namespaceSelector:
    matchNames:
      {{- tpl ("serviceMonitor.namespaceSelector.matchNames" | toYaml) . | nindent 4 }}
  selector:
    matchLabels:
      {{- tpl ("serviceMonitor.selector.matchLabels" | toYaml) . | nindent 4 }}
{{- end }}
