{{- if .Values.server.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: { { .Values.global.name } }
    group: { { .Values.global.group } }
    org: { { .Values.global.org } }
  name: { { .Values.global.name } }
  namespace: { { .Values.global.namespace } }
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: health-port
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
  selector:
    matchLabels:
      app: { { .Values.global.name } }
{{- end -}}
