{{- if .Values.server.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: { { .Values.global.name } }
    env: { { .Values.global.env } }
    group: { { .Values.global.group } }
    lang: { { .Values.language } }
    org: { { .Values.global.org } }
  name: { { .Values.global.name } }
  namespace: { { .Values.global.namespace } }
spec:
  ports:
    - name: service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: health-port
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: { { .Values.global.name } }
    group: { { .Values.global.group } }
    org: { { .Values.global.org } }
{{- end -}}
