{{- if ( .Values.service.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- tpl ("metadata.labels" | toYaml) . | nindent 4 }}
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
{{- range .Values.service.ports}}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
{{- end }}
  selector:
    {{- tpl ("selector.labels" | toYaml) . | nindent 4 }}
  replicas: 2
  template:
    metadata:
      labels:
        run: {{ .Values.global.name }}
    spec:
      containers:
      - name: {{ .Values.global.name }}
        image: {{ .Values.global.image }}
        ports:
        {{ .Values.service.container.port }}
{{- end }}
